#ifndef PUB_SUB_H
#define PUB_SUB_H

enum Message {
  NEW_OBJECT_TEMPERATURE,
  NEW_ON_DIE_TEMPERATURE,
  NEW_ROOM_TEMPERATURE,
  NEW_BATTERY_TEMPERATURE,
  
  SET_EMISSIVITY,
  NEW_EMISSIVITY_READING,
  
  NEW_BATTERY_PERCENTAGE,
  NEW_BATTERY_CHARGING_STATUS,
  
  BAD_AUTH_ATTEMPT,
  SUCCESSFUL_AUTH,
  
  NEW_OBJECT_TEMPERATURE_SMOOTHING,
  SET_OBJECT_TEMPERATURE_SMOOTHER_FACTOR,
  
  NEW_CALIBRATION_BOARD_CONNECTION,
  
  NEW_PRIMARY_THERMISTOR_TEMPERATURE,
  NEW_SECONDARY_THERMISTOR_TEMPERATURE,
  
  SET_LOW_POWER_MODE_TIMEOUT,
  NEW_LOW_POWER_MODE_TIMEOUT,
  SET_POWER_OFF_TIMEOUT,
  NEW_POWER_OFF_TIMEOUT,
  
  NEW_POWER_INDICATOR_ON_BRIGHTNESS,
  NEW_POWER_INDICATOR_MAX_BREATH_BRIGHTNESS,
  SET_POWER_INDICATOR_ON_BRIGHTNESS,
  SET_POWER_INDICATOR_MAX_BREATH_BRIGHTNESS,

  NEW_ROOM_TEMPERATURE_OFFSET,
  SET_ROOM_TEMPERATURE_OFFSET,

  NEW_DISPLAY_BRIGHTNESS,
  SET_DISPLAY_BRIGHTNESS
};

#endif // !PUB_SUB_H