#ifndef PUB_SUB_H
#define PUB_SUB_H

enum Message {
  NEW_OBJECT_TEMPERATURE_MSG,
  NEW_AMBIENT_TEMPERATURE_MSG,
  NEW_THERMISTOR_TEMPERATURE_MSG,
  SET_EMISSIVITY_MSG,
  NEW_EMISSIVITY_READING_MSG,
  NEW_BATTERY_PERCENTAGE_MSG,
  NEW_BATTERY_CHARGING_STATUS_MSG,
  BAD_AUTH_ATTEMPT_MSG,
  SUCCESSFUL_AUTH_MSG,
  NEW_OBJECT_TEMPERATURE_SMOOTHING_MSG,
  NEW_AMBIENT_TEMPERATURE_SMOOTHING_MSG,
  NEW_THERMISTOR_TEMPERATURE_SMOOTHING_MSG,
  SET_OBJECT_TEMPERATURE_SMOOTHER_FACTOR_MSG,
  SET_AMBIENT_TEMPERATURE_SMOOTHER_FACTOR_MSG,
  SET_THERMISTOR_TEMPERATURE_SMOOTHER_FACTOR_MSG
};

#endif // !PUB_SUB_H